package communication;

public enum MessageType{
    DP_NO_MORE_PASSENGERS,
    DP_IS_PLANE_BOARDED,
    PLANE_GET_NUMBER,
    HOSTESS_PREPARE_FOR_BOARDING,
    HOSTESS_CHECK_DOCUMENTS,
    HOSTESS_WAIT_FOR_NEXT_PASSENGER,
    HOSTESS_WAIT_FOR_NEXT_FLIGHT,
    HOSTESS_INFORM_PLANE_READY,
    PASSENGER_TRAVEL_AIRPORT,
    PASSENGER_WAIT_QUEUE,
    PASSENGER_SHOW_DOCUMENTS,
    PASSENGER_LEAVE_PLANE,
    PASSENGER_BOARD_PLANE,
    PASSENGER_WAIT_FOR_END,
    PASSENGER_EXIT,
    PILOT_FLY_DESTINATION_POINT,
    PILOT_PARK_TRANSFER_GATE,
    PILOT_INFORM_TAKEOFF,
    PILOT_WAIT_ALL_INBOARD,
    PILOT_ANNOUNCE_ARRIVAL,
    PILOT_FLY_DEPARTURE_POINT
}